package CatalystBasic::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'CatalystBasic::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:user',
        user => 'admin',
        password => 'admin',
    }
);

=head1 NAME

CatalystBasic::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<CatalystBasic>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<CatalystBasic::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

lequochuy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
